---
dependency:
  name: galaxy
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
driver:
  name: docker
platforms: 
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian9}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: .vault_pass.txt
verifier:
  name: ansible
